[package]
name = "slsconfigurator"
version = "0.1.0"
edition = "2021"
description = "TUI editor for the SLSsteam config"
license = "MIT"

[[bin]]
name = "slsconfigurator"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
ratatui = "0.30.2"
yaml-edit = "0.3.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
